version: "3.8"

services:
  cat-service:
    image: kkdohyeong/devview:${IMAGE_TAG:-latest}
    container_name: cat-service
    restart: always
    ports:
      - "8000:8080"
    env_file:
      - .env            # Jenkins가 덮어쓰는 파일
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks: [ backend ]

networks:
  backend:
    driver: bridge
