version: '3.1'

services:
  cat-service:
    image: kkdohyeong/devview:1.0
    container_name: cat-service
    ports:
      - "8000:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod  # 나머지는 .env 가 자동 주입
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
