version: "3.8"

services:
  cat-service:
    image: kkdohyeong/devview
    container_name: cat-service
    ports:
      - "8000:8080"
    env_file:
      - .prodenv            # Jenkins가 덮어쓰는 파일
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks: [ backend ]

networks:
  backend:
    driver: bridge
